### ISSUE TITLE
Revision of material - team Harkonnen

### ISSUE THREAD

**Issue by essepuntato** [open-sci/2023-2024#28]
Dear @open-sci/harkonnen,

Please find here attached my comments on all your material. You have to address all of them and, once finalised, to close this issue with a comment containing your reply to each of the points I have highlighted. There is no specific deadline to complete this task, thus please take your time.

Please, be aware that some modifications in some documents may affect also modifications in other documents. As a final note, please remember to keep your notebooks up-to-date.

After closing this issue, please remember to update your material.md file by specifying the references to the new version of all your documents.

As usual, for further doubts, do not hesitate to contact me in the Slack channel or just comment on this issue here.

# General comments from the presentation

- During the presentation, there was a comment about how many non-anonymous reviews are present in the dataset. It would be important, to some extent, to understand that, also in percentage, and if it relates to specific venues or not.

# DMP

- The DMP should be available in PDF, but a DOCX was found in Zenodo.

- Honestly, the name of the datasets should not contain the term "Description of" but just their name.

### 1.1.5 What is its format?
- ".turtle" is not an extension; ".ttl" is.

### 2.3.1 Does the described output use or support any software?
- Should not be the opposite, i.e. the fact that the dataset has been created by means of the software (thus, is the software supporting the data, not vice versa)?

### 3.2.1.1 In which repository will the dataset / output be deposited?
- Did you use Zenodo for the data? Why GitHub?

### 3.2.2.9 Please specify how the dataset / output will be accessed during and after the project ends
- ISC is for software, not for data...

### 3.4.1 What internationally recognised licence will you use for your dataset / output?
- See above.

### 4.1.3 Identify the people who will be responsible and their role(s) in the management of the described output
- Bad layout of text in the section, please fix it.

### 5.1.3 How will you preserve the described dataset / output in the long term?
- The DOI does not guarantee preservation, Zenodo does!

### 6.1.3 Does the described dataset / output contain personal data?
- Does not it contain author names? If it contains that, then they are personal data - even if there is an exception that enable their publication in case of bibliographic data though.

### 3.2.1.1 In which repository will the dataset / output be deposited?
- As before, are you using Zenodo for the deposit? Also because GitHub does not assign any PID for it...

### 3.2.2.1 What is the described dataset / output title?
- That is the name of the dataset, not of the software, right?

### 4.1.3 Identify the people who will be responsible and their role(s) in the management of the described output
- Bad layout of text in the section, please fix it.

# Protocol

- The presence of the structured abstract here is out of context, since the protocol should explain the procedure, not to offer the results.

- The note about your computer capabilities should not be put explicitly there, but added as a note. However, you should specify how much available space and computing power one is supposed to have to address the protocol correctly.

- In sections 2.1, 3.1, ..., you are talking about implementation things (argparse, classes, method, etc.). You should talk, instead, about what you need to address and then, if needed, refer to a script you developed to perform that passage. Indeed, section 2.1 seems more like a code documentation than a workflow. How does someone know what to do to replicate the process? Explain how you the process works from an abstract perspective (without mentioning to explicit methods and class) and then show at the end of each section how to run the code. In addition, you should describe which input and output are used and produced, with examples.

- As a side note, by reading the text, it seems that you first developed the code and then wrote the protocol. It is the other way round, and the protocol should be specific and generic enough to be understandable and replicable. Of course, you can include how to run scripts, but you should not explain how classes and methods work here.

# Software

- The GitHub repository does not contain any information about the code in the readme. It should contain a general description, information about which hardware and other software are necessary to run it, and instructions for running it.

# Data

- You uploaded three different datasets on Zenodo, describing different perspectives of the analysis you did. However, the DMP only contains a reference for one dataset. Thus, you have to revise the DMP to match with your actual dataset publications.

# Article

## Abstract
- Please use the structured abstract, with the labels describing each section of it.
- Abstract has no number.

## Introduction
- Section number should start here with "1".

## Results
- In Table 1, please substitute "NaN" with a term that is more intelligible, such as "n/a".

- In Table 1, what if a journal has more than two ISSNs? Sometimes, this may happen. As a suggestion, I would put all the ISSNs found in a space-separated list under the same column. If you want to leave them in two columns, fine, but then it should not be ISSN1 and ISSN2 but rather ISSN and E-ISSN, and you should understand what is what.

- What is the difference between Table 1 and Figure 6? Keep just one of them, the most informative (which is the table...).

- In table 1, it is not clear what that count refers to. Even the legend is too ambiguous.

- Figure 11 does not make it clear what it is about by reading the legend. How is it even possible that those venues do not have an ISSN? They are journals!

# Presentation

- Please provide the appropriate reference for the slides since there is only the DOI so far.

**Comment by ChiaraParravicini** [comment]
# General comments from the presentation
We re-ran the code for extracting peer-reviews, adding a section dedicated to collecting author information (first name, last name, and ORCID, if available). Once done so, we proceed with descriptive analysis over this new data extracting the percentage of anonymous and non-anonymous peer reviews, the top ten venues per number of non-anonymous peer reviews received and the number of authors per peer review when not anonymous.

# DMP
The DMP has been revised to correct oversights and errors. Additionally, suggestions regarding the resource names, their hierarchy, and information on privacy and preservation have been incorporated. The file has been saved and re-uploaded to Zenodo in the correct format and layout.

# Protocol
- We replaced the structured abstract with a more concise version, which highlights the main purpose of our project, our research questions, and the key steps of the methodology we followed.

- The specification about the available space and computing power needed has been added in the "Before starting" section; the note about our computer capabilities has been included in the "Warnings" section.

- The entire protocol has been revised to describe the workflow rather than the code, ensuring that the methodology is easily understandable and replicable. Each step is now presented from an abstract perspective, specifying inputs and expected results.

# Software
The repository has been heavily modified, now it contains a well structured readme with a synthetic description of the flow and of the repository’s structure itself. Information about the required hardware/software necessary to correctly run everything has been added. A proper “requirements.txt” file has been added in order to enable the user to install all the correct libraries easily.

# Article
## Abstract
The abstract was rewritten following the indicated structure and the number was removed.

## Introduction
According to the previous change the introduction updated presents number 1.

## Results
- In Table 1, the “NaN” values were replaced with “n/a”
- In Table 1, we combined the values in the two columns headers “ISSN 1” and “ISSN 2” into a unique column named ISSNs. 
- Figure 6 was removed.
- The column in Table 1 were renamed as follow: 
a. “Cited venue” => “Title of the venue” (also moved as first column
b. “issn 1” and “issn 2” => single column “ISSNs”
c. “Count” => “Peer reviews received”

- Figure 11 (Now Figure 10) has a new description “Ten most cited venues where no ISSN was extracted from Crossref”

# Presentation
The appropriate reference from Zenodo has been added.
